companystatistics/auth_app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy, include
from rest_framework import routers

from . import views

app_name = 'auth_app'

router = routers.DefaultRouter()
router.register(r'users', views.CSUserViewSet)

urlpatterns = [
    path('api/', include(router.urls)),

    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('edit/', views.UserEditView.as_view(), name='edit'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),

    # # change password urls
    # path('password_change/',
    #      # auth_views.PasswordChangeView.as_view(
    #      views.CSPasswordChangeView.as_view(
    #          # success_url=reverse_lazy('auth_app:password_change_done')
    #      ),
    #      name='password_change'),
    # path('password_change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(),
    #      name='password_change_done'),
    #
    # # reset password urls
    # path('password_reset/',
    #      # auth_views.PasswordResetView.as_view(
    #      views.CSPasswordResetView.as_view(
    #          # success_url=reverse_lazy('auth_app:password_reset_done')
    #      ),
    #      name='password_reset'),
    # path('password_reset_done/done/',
    #      auth_views.PasswordResetDoneView.as_view(),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #      # auth_views.PasswordResetConfirmView.as_view(
    #      views.CSPasswordResetConfirmView.as_view(
    #         # success_url = reverse_lazy('auth_app:password_reset_complete')
    #      ),
    #      name='password_reset_confirm'),
    # path('reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(),
    #      name='password_reset_complete'),
]

companystatistics/companystatistics/urls.py
from django.contrib import admin
from django.urls import path, include

from stat_app.views import DepartmentListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('stat/', include('stat_app.urls', namespace='stat_app')),
    path('', DepartmentListView.as_view(), name='department_list'),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

companystatistics/stat_app/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view

from . import views

app_name = 'stat_app'

router = routers.DefaultRouter()
router.register(r'companies', views.CompanyViewSet)
router.register(r'departments', views.DepartmentViewSet)
router.register(r'stat_titles', views.StatTitleViewSet)
router.register(r'stats', views.StatViewSet)

# schema_view = get_schema_view(title='Stat API', description='An API to manage statistics.')

urlpatterns = [
    path('company/<slug:company>/',
         views.DepartmentListView.as_view(),
         name='department_list_company'),
    path('<slug:slug>/',
         views.DepartmentDetailView.as_view(),
         name='department_detail'),
    path('<int:department_id>/stat_title_create/',
         views.stat_title_create,
         name='stat_title_create'),
    path('<int:stat_title_id>/stat_create/',
         views.stat_create,
         name='stat_create'),
    path('<int:stat_id>/stat_edit/',
         views.stat_edit,
         name='stat_edit'),

    path('api/data/', views.get_data, name='api-data'),

    path('api/', include(router.urls)),
    # path('schema/', schema_view),
    # path('docs/', include_docs_urls(title='Stat API'))
]

companystatistics/main_app/models.py
from django.db import models

# Create your models here.

companystatistics/main_app/views.py
from django.shortcuts import render

companystatistics/main_app/templates/main_app/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block css %}
        <!-- Bootstrap CSS -->
        <link
                rel="stylesheet"
                href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
                integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
                crossorigin="anonymous"
        >
        <link
                rel="stylesheet"
                href="{% static 'css/style.css' %}"
        >
    {% endblock %}

    <title>
        {% block title %}
            Company Statistics | {{ page_title|title }}
        {% endblock %}
    </title>
</head>
<body>

<header>
    {% include 'main_app/includes/navbar.html' %}
</header>

<!-- Begin page content -->
<main role="main">
    <div class="container mt-3">
        {% block content %}
        {% endblock %}
    </div>
</main>

{#{% include 'main_app/includes/footer.html' %}#}

{% include 'main_app/includes/js.html' %}

{% block javascript %}
{% endblock %}

</body>
</html>

companystatistics/main_app/templates/main_app/index.html
{% extends 'main_app/base.html' %}

{% block title %}
    {% if company %}
        Отделы компании: {{ company.title }}
    {% else %}
        Все отделы
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row">

        <div class="col-3 p-3 mb-2 bg-secondary text-white">
            <h3>Компании</h3>
            <ul id="cards" class="list-group">
                <li {% if not company %}class="list-group-item list-group-item-primary"
                    {% else %}class="list-group-item"{% endif %}>
                    <a href="{% url "department_list" %}">Все</a>
                </li>
                {% for c in companies %}
                    <li {% if company == c %}class="list-group-item list-group-item-primary"
                        {% else %}class="list-group-item"{% endif %}>
                        <a href="{% url "stat:department_list_company" c.slug %}">
                            {{ c.title }}
                            <br><span>Отделов: {{ c.total_departments }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div class="col-9">
            <div class="card">
                <div class="card-header">
                    <h3>
                        {% if company %}
                            Отделы компании {{ company.title }}
                        {% else %}
                            Все отделы
                        {% endif %}
                    </h3>
                </div>
                <div class="card-body">
                    {% for department in departments %}
                        {% with company=department.company %}
                            <h4>
                                <a href="{% url "stat:department_detail" department.slug %}">{{ department.title }}</a>
                            </h4>
                            <p class="card-text">
                                <a href="{% url "stat:department_list_company" company.slug %}">{{ company }}</a>.
                                Форм: {{ department.total_stat_titles }}.
                            </p>
                        {% endwith %}
                        {% empty %}
                        <p class="card-text">Нет отделов</p>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>
{% endblock %}