companystatistics/auth_app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy, include
from rest_framework import routers

from . import views

app_name = 'auth_app'

router = routers.DefaultRouter()
router.register(r'users', views.CSUserViewSet)

urlpatterns = [
    path('api/', include(router.urls)),

    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('edit/', views.UserEditView.as_view(), name='edit'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),

    # # change password urls
    # path('password_change/',
    #      # auth_views.PasswordChangeView.as_view(
    #      views.CSPasswordChangeView.as_view(
    #          # success_url=reverse_lazy('auth_app:password_change_done')
    #      ),
    #      name='password_change'),
    # path('password_change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(),
    #      name='password_change_done'),
    #
    # # reset password urls
    # path('password_reset/',
    #      # auth_views.PasswordResetView.as_view(
    #      views.CSPasswordResetView.as_view(
    #          # success_url=reverse_lazy('auth_app:password_reset_done')
    #      ),
    #      name='password_reset'),
    # path('password_reset_done/done/',
    #      auth_views.PasswordResetDoneView.as_view(),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #      # auth_views.PasswordResetConfirmView.as_view(
    #      views.CSPasswordResetConfirmView.as_view(
    #         # success_url = reverse_lazy('auth_app:password_reset_complete')
    #      ),
    #      name='password_reset_confirm'),
    # path('reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(),
    #      name='password_reset_complete'),
]

companystatistics/companystatistics/urls.py
from django.contrib import admin
from django.urls import path, include

from stat_app.views import DepartmentListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('stat/', include('stat_app.urls', namespace='stat_app')),
    path('', DepartmentListView.as_view(), name='department_list'),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

companystatistics/stat_app/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view

from . import views

app_name = 'stat_app'

router = routers.DefaultRouter()
router.register(r'companies', views.CompanyViewSet)
router.register(r'departments', views.DepartmentViewSet)
router.register(r'stat_titles', views.StatTitleViewSet)
router.register(r'stats', views.StatViewSet)

# schema_view = get_schema_view(title='Stat API', description='An API to manage statistics.')

urlpatterns = [
    path('company/<slug:company>/',
         views.DepartmentListView.as_view(),
         name='department_list_company'),
    path('<slug:slug>/',
         views.DepartmentDetailView.as_view(),
         name='department_detail'),
    path('<int:department_id>/stat_title_create/',
         views.stat_title_create,
         name='stat_title_create'),
    path('<int:stat_title_id>/stat_create/',
         views.stat_create,
         name='stat_create'),
    path('<int:stat_id>/stat_edit/',
         views.stat_edit,
         name='stat_edit'),

    path('api/data/', views.get_data, name='api-data'),

    path('api/', include(router.urls)),
    # path('schema/', schema_view),
    # path('docs/', include_docs_urls(title='Stat API'))
]

companystatistics/stat_app/models.py
from django.conf import settings
from django.db import models
from django.contrib.contenttypes.models import ContentType


class Company(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        verbose_name = 'компания'
        verbose_name_plural = 'компании'
        ordering = ['title']

    def __str__(self):
        return self.title


class Department(models.Model):
    company = models.ForeignKey(Company,
                                related_name='departments',
                                on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    overview = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = 'отдел'
        verbose_name_plural = 'отделы'
        ordering = ['title']

    def __str__(self):
        return self.title


class StatTitle(models.Model):
    department = models.ForeignKey(Department,
                                   related_name='stat_titles',
                                   on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    overview = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = 'форма'
        verbose_name_plural = 'формы'
        ordering = ['title']

    def __str__(self):
        return self.title


class Stat(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   related_name='statistics_created',
                                   on_delete=models.DO_NOTHING)
    title = models.ForeignKey(StatTitle,
                              related_name='stats',
                              on_delete=models.CASCADE,)
    amount = models.DecimalField(decimal_places=2, max_digits=12)
    date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'данные'
        verbose_name_plural = 'данные'
        ordering = ['date']

    def __str__(self):
        return f'{self.date} | {self.amount} | {self.owner}'

companystatistics/stat_app/forms.py
from django import forms

from .models import Stat, StatTitle


class StatForm(forms.ModelForm):

    class Meta:
        model = Stat
        fields = ('amount', 'date',)


class StatTitleForm(forms.ModelForm):

    class Meta:
        model = StatTitle
        fields = ('title', 'overview',)

companystatistics/stat_app/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView
from django.views.generic.base import TemplateResponseMixin, View
from rest_framework import viewsets, permissions, status
from rest_framework.response import Response

from .forms import StatForm, StatTitleForm
from .models import Department, Company, StatTitle, Stat
from .serializers import CompanySerializer, DepartmentSerializer, StatTitleSerializer, StatSerializer


class DepartmentListView(LoginRequiredMixin, TemplateResponseMixin, View):
    model = Department
    template_name = 'stat_app/department/list.html'

    def get(self, request, company=None):
        companies = Company.objects.annotate(
            total_departments=Count('departments'))
        departments = Department.objects.annotate(
            total_stat_titles=Count('stat_titles'))
        if company:
            company = get_object_or_404(Company, slug=company)
            departments = departments.filter(company=company)

        return self.render_to_response({'companies': companies,
                                        'company': company,
                                        'departments': departments})


class DepartmentDetailView(LoginRequiredMixin, DetailView):
    model = Department
    template_name = 'stat_app/department/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DepartmentDetailView,
                        self).get_context_data(**kwargs)
        stat_titles = StatTitle.objects.filter(department=self.object)
        stats = Stat.objects.all()
        context['stat_titles'] = stat_titles
        context['stats'] = stats

        return context


def stat_create(request, stat_title_id):
    stat_title = StatTitle.objects.filter(id=stat_title_id).first()
    if request.method == "POST":
        form = StatForm(request.POST)
        if form.is_valid():
            stat = form.save(commit=False)
            stat.owner = request.user
            stat.title = stat_title
            stat.save()
            return redirect('department_list')
    else:
        form = StatForm()
    context = {
        'form': form,
        'stat_title': stat_title.title,
    }
    return render(request, 'stat_app/stat/form.html', context)


def stat_edit(request, stat_id):
    stat = get_object_or_404(Stat, id=stat_id)
    if request.method == "POST":
        form = StatForm(request.POST, instance=stat)
        if form.is_valid():
            stat = form.save(commit=False)
            stat.owner = request.user
            stat.save()
            return redirect('department_list')
    else:
        form = StatForm(instance=stat)
    context = {
        'form': form,
        'stat_title': stat.title,
        'object': stat,
    }
    return render(request, 'stat_app/stat/form.html', context)


def stat_title_create(request, department_id=None):
    if department_id:
        department = Department.objects.filter(id=department_id).first()
        if request.method == "POST":
            form = StatTitleForm(request.POST)
            if form.is_valid():
                stat_title = form.save(commit=False)
                stat_title.department = department
                stat_title.save()
                return redirect('stat_app:department_detail', department.slug)
        else:
            form = StatTitleForm()
        context = {
            'form': form,
            'department': department,
        }
        return render(request, 'stat_app/stat_title/form.html', context)


def get_data(request, *args, **kwargs):
    stats = Stat.objects.all()

    stats_dict = {str(StatTitle.objects.filter(title=stat.title).first().id): {'default': [], 'labels': []} for stat in
                  stats}

    for stat in stats:
        stats_dict[str(StatTitle.objects.filter(title=stat.title).first().id)]['default'].append(float(stat.amount))
        stats_dict[str(StatTitle.objects.filter(title=stat.title).first().id)]['labels'].append(str(stat.date))
    data = {
        'stats_dict': stats_dict,
    }

    return JsonResponse(data)


class CompanyViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows companies to be viewed or edited.
    """
    queryset = Company.objects.all().order_by('title')
    serializer_class = CompanySerializer
    # permission_classes = [permissions.IsAuthenticated]

    def get_permissions(self):
        """
        Instantiates and returns the list of permissions that this view requires.
        """
        if self.action in ['list', 'retrieve']:
            permission_classes = [permissions.IsAuthenticated]
        else:
            permission_classes = [permissions.IsAdminUser]
        return [permission() for permission in permission_classes]


class DepartmentViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows departments to be viewed or edited.
    """
    queryset = Department.objects.all().order_by('title')
    serializer_class = DepartmentSerializer

    def get_permissions(self):
        """
        Instantiates and returns the list of permissions that this view requires.
        """
        if self.action in ['list', 'retrieve']:
            permission_classes = [permissions.IsAuthenticated]
        else:
            permission_classes = [permissions.IsAdminUser]
        return [permission() for permission in permission_classes]

    # def perform_create(self, serializer):
    #     company_id = self.kwargs.get('company_id')
    #     company = get_object_or_404(Company, id=company_id)
    #     serializer.save(company=company)

    def create(self, request, *args, **kwargs):
        try:
            item = request.data
            if not (item.get('title') and item.get('slug')):
                raise AttributeError
            company_id = item.get('company')
            company = get_object_or_404(Company, id=company_id)
            item['company'] = company
            department = Department.objects.create(**item)
            return Response(status=status.HTTP_201_CREATED)
        except AttributeError:
            return Response(status=status.HTTP_400_BAD_REQUEST)

    def update(self, request, *args, **kwargs):
        try:
            query_dict = request.data
            item = dict(query_dict.items())
            department_id = kwargs.get('pk')
            if not department_id:
                raise AttributeError
            Department.objects.filter(id=department_id).update(**item)
            return Response(status=status.HTTP_200_OK)
        except AttributeError:
            return Response(status=status.HTTP_400_BAD_REQUEST)


class StatTitleViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows stat_titles to be viewed or edited.
    """
    queryset = StatTitle.objects.all().order_by('title')
    serializer_class = StatTitleSerializer

    def get_permissions(self):
        """
        Instantiates and returns the list of permissions that this view requires.
        """
        if self.action in ['list', 'retrieve']:
            permission_classes = [permissions.IsAuthenticated]
        else:
            permission_classes = [permissions.IsAdminUser]
        return [permission() for permission in permission_classes]

    def create(self, request, *args, **kwargs):
        try:
            item = request.data
            if not item.get('title'):
                raise AttributeError
            department_id = item.get('department')
            department = get_object_or_404(Department, id=department_id)
            item['department'] = department
            StatTitle.objects.create(**item)
            return Response(status=status.HTTP_201_CREATED)
        except AttributeError:
            return Response(status=status.HTTP_400_BAD_REQUEST)

    def update(self, request, *args, **kwargs):
        try:
            query_dict = request.data
            item = dict(query_dict.items())
            id_ = kwargs.get('pk')
            if not id_:
                raise AttributeError
            StatTitle.objects.filter(id=id_).update(**item)
            return Response(status=status.HTTP_200_OK)
        except AttributeError:
            return Response(status=status.HTTP_400_BAD_REQUEST)


class StatViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows stats to be viewed or edited.
    """
    queryset = Stat.objects.all().order_by('-date')
    serializer_class = StatSerializer

    def get_permissions(self):
        """
        Instantiates and returns the list of permissions that this view requires.
        """
        if self.action in ['list', 'retrieve', 'create']:
            permission_classes = [permissions.IsAuthenticated]
        else:
            permission_classes = [permissions.IsAdminUser]
        return [permission() for permission in permission_classes]

    def create(self, request, *args, **kwargs):
        try:
            item = request.data
            if not (item.get('amount') and item.get('date')):
                raise AttributeError
            owner_id = item.get('owner')
            stat_title_id = item.get('title')
            owner = get_object_or_404(get_user_model(), id=owner_id)
            title = get_object_or_404(StatTitle, id=stat_title_id)
            item['owner'] = owner
            item['title'] = title
            Stat.objects.create(**item)
            return Response(status=status.HTTP_201_CREATED)
        except AttributeError:
            return Response(status=status.HTTP_400_BAD_REQUEST)

    def update(self, request, *args, **kwargs):
        try:
            query_dict = request.data
            item = dict(query_dict.items())
            id_ = kwargs.get('pk')
            if not id_:
                raise AttributeError
            Stat.objects.filter(id=id_).update(**item)

companystatistics/stat_app/templates/stat_app/department/detail.html
{% extends 'main_app/base.html' %}
{% load crispy_forms_tags %}
{% load plotly_dash %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block content %}
    <div class="row">
        {% with company=department.company %}

            <div class="col-3 p-3 mb-2 bg-secondary">
                <div class="card">
                    <div class="card-header">
                        <h2>
                            {{ object.title }}
                        </h2>
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">Описание:</h3>
                        <p class="card-text">
                            <a href="{% url 'stat_app:department_list_company' company.slug %}">{{ company.title }}</a>.
                        </p>
                        {% if object.overview %}
                            <p class="card-text">
                                {{ object.overview|linebreaks }}
                            </p>
                        {% endif %}
                    </div>

                    {% if request.user.is_staff %}
                        <div class="card-footer">
                            <a href="{% url 'stat_app:stat_title_create' department.id %}"
                               class="btn btn-primary">
                                Добавить форму
                            </a>
                        </div>
                    {% endif %}

                </div>
            </div>

            <div class="col-9">
                {% for stat_title in stat_titles %}
                    <div class="row">
                        <div class="col-12">
                            <div class="card mb-3">
                                <div class="card-header">
                                    <h3>
                                        {#                                        {{ stat_title }} <a class="btn btn-link" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Скрыть/Показать</a>#}
                                        {{ stat_title }} <a class="btn btn-link" data-toggle="collapse"
                                                            href="#collapse{{ stat_title.id }}" role="button"
                                                            aria-expanded="false"
                                                            aria-controls="collapse{{ stat_title.id }}">Скрыть/Показать</a>
                                    </h3>

                                </div>
                                <div class="card-body">
                                    {% if request.user.is_staff %}
                                        <div class="collapse" id="collapse{{ stat_title.id }}">
                                            <canvas id="myChart{{ stat_title.id }}" width="400" height="150"></canvas>
                                            {% plotly_app name="SimpleExample" %}
                                            <ul class="list-group">
                                                {% for s in stats %}
                                                    {% if s.title == stat_title %}
                                                        <li class="list-group-item">
                                                            {{ s.date }} - {{ s.amount }} ({{ s.owner }})
                                                            <a href="{% url 'stat_app:stat_edit' s.id %}"
                                                               class="btn btn-link">
                                                                Изменить данные
                                                            </a>
                                                        </li>
                                                    {% endif %}
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    {% endif %}
                                    <a href="{% url 'stat_app:stat_create' stat_title.id %}"
                                       class="btn btn-primary mt-3">
                                        Добавить данные
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <div class="card">
                        <div class="card-body">
                            Нет форм
                        </div>
                    </div>
                {% endfor %}
            </div>

        {% endwith %}
    </div>

{% endblock %}

{% block javascript %}
    <script>
        var endpoint = '/stat/api/data/';
        var stats_dict = {};
        $.ajax({
            method: 'GET',
            url: endpoint,
            success: function (data) {
                stats_dict = data.stats_dict;
                setCart()
            },
            error: function (error_data) {
                console.log('error');
                console.log(error_data);
            }
        });

        function setCart() {
            for (let statTitleId in stats_dict) {
                var ctx = document.getElementById('myChart' + statTitleId);
                var myChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: stats_dict[statTitleId].labels,
                        datasets: [{
                            label: 'Выручка',
                            data: stats_dict[statTitleId].default,
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }
                })
            }
        }
    </script>
{% endblock %}

companystatistics/stat_app/templates/stat_app/department/list.html
{% extends 'main_app/base.html' %}

{% block title %}
    {% if company %}
        Отделы компании: {{ company.title }}
    {% else %}
        Все отделы
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row">

        <div class="col-3 p-3 mb-2 bg-secondary text-white">
            <h3>Компании</h3>
            <ul id="cards" class="list-group">
                <li {% if not company %}class="list-group-item list-group-item-primary"
                    {% else %}class="list-group-item"{% endif %}>
                    <a href="{% url "department_list" %}">Все</a>
                </li>
                {% for c in companies %}
                    <li {% if company == c %}class="list-group-item list-group-item-primary"
                        {% else %}class="list-group-item"{% endif %}>
                        <a href="{% url "stat_app:department_list_company" c.slug %}">
                            {{ c.title }}
                            <br><span>Отделов: {{ c.total_departments }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div class="col-9">
            <div class="card">
                <div class="card-header">
                    <h3>
                        {% if company %}
                            Отделы компании {{ company.title }}
                        {% else %}
                            Все отделы
                        {% endif %}
                    </h3>
                </div>
                <div class="card-body">
                    {% for department in departments %}
                        {% with company=department.company %}
                            <h4>
                                <a href="{% url "stat_app:department_detail" department.slug %}">{{ department.title }}</a>
                            </h4>
                            <p class="card-text">
                                <a href="{% url "stat_app:department_list_company" company.slug %}">{{ company }}</a>.
                                Форм: {{ department.total_stat_titles }}.
                            </p>
                        {% endwith %}
                        {% empty %}
                        <p class="card-text">Нет отделов</p>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>
{% endblock %}