companystatistics/auth_app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy, include
from rest_framework import routers

from . import views

app_name = 'auth_app'

router = routers.DefaultRouter()
router.register(r'users', views.CSUserViewSet)

urlpatterns = [
    path('api/', include(router.urls)),

    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('edit/', views.UserEditView.as_view(), name='edit'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),

    # # change password urls
    # path('password_change/',
    #      # auth_views.PasswordChangeView.as_view(
    #      views.CSPasswordChangeView.as_view(
    #          # success_url=reverse_lazy('auth_app:password_change_done')
    #      ),
    #      name='password_change'),
    # path('password_change/done/',
    #      auth_views.PasswordChangeDoneView.as_view(),
    #      name='password_change_done'),
    #
    # # reset password urls
    # path('password_reset/',
    #      # auth_views.PasswordResetView.as_view(
    #      views.CSPasswordResetView.as_view(
    #          # success_url=reverse_lazy('auth_app:password_reset_done')
    #      ),
    #      name='password_reset'),
    # path('password_reset_done/done/',
    #      auth_views.PasswordResetDoneView.as_view(),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #      # auth_views.PasswordResetConfirmView.as_view(
    #      views.CSPasswordResetConfirmView.as_view(
    #         # success_url = reverse_lazy('auth_app:password_reset_complete')
    #      ),
    #      name='password_reset_confirm'),
    # path('reset/done/',
    #      auth_views.PasswordResetCompleteView.as_view(),
    #      name='password_reset_complete'),
]

companystatistics/companystatistics/urls.py
from django.contrib import admin
from django.urls import path, include

from stat_app.views import DepartmentListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('stat/', include('stat_app.urls', namespace='stat_app')),
    path('', DepartmentListView.as_view(), name='department_list'),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

companystatistics/main_app/models.py
from django.db import models

# Create your models here.

companystatistics/main_app/views.py
from django.shortcuts import render

companystatistics/main_app/templates/main_app/includes/footer.html
<footer class="footer">
    <div class="container">
        <div class="row text-muted">
            <div class="col-3 mx-auto">
                CompanyStatistics
{#                <p class="mt-0">CompanyStatistics - приложение для управления статистикой компании</p>#}
            </div>
            <div class="col-6 mx-auto">
                support@companystatistics.local
            </div>
        </div>
    </div>
</footer>

companystatistics/main_app/templates/main_app/includes/js.html
<script
  src="http://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>

companystatistics/main_app/templates/main_app/includes/navbar.html
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url "department_list" %}">Company Statistics</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "department_list" %}">Компании <span
                                class="sr-only">(current)</span></a>
                    </li>
                    {#                <li class="nav-item">#}
                    {#                    <a class="nav-link" href="#">Link</a>#}
                    {#                </li>#}
                    {#                <li class="nav-item">#}
                    {#                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
                    {#                </li>#}
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto px-3">
                {% if request.user.is_authenticated %}
                    <li class="nav-item text-nowrap">
                        <a class="nav-link" href="{% url "auth_app:logout" %}">Выйти</a>
                    </li>
                    {% if page_title != "edit" and page_title != "редактировать" %}
                        <li class="nav-item text-nowrap">
                            <a class="nav-link" href="{% url "auth_app:edit" %}">Редактировать</a>
                        </li>
                    {% endif %}
                    {% if page_title != "profile" and page_title != "профиль" %}
                        <li class="nav-item text-nowrap">
                            <a class="nav-link" href="{% url "auth_app:profile" %}">Профиль ({{ request.user }})</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="nav-item text-nowrap">
                        <a class="nav-link" href="{% url "auth_app:login" %}">Войти</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>